vich_uploader:
    db_driver: orm

    metadata:
        type: attribute
    mappings:
        siteweb:
            uri_prefix: /images/siteweb
            upload_destination: '%kernel.project_dir%/public/images/siteweb'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer